change(prof-get): now NEIGH_MAC also detect stale neighbours
style changed by VS Code

diff --git a/bin/msc-prof-get b/bin/msc-prof-get
--- a/bin/msc-prof-get
+++ b/bin/msc-prof-get
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -eu         # Exit when returns non-zero, Error when variable is unset.
+set -eu # Exit when returns non-zero, Error when variable is unset.
 ### NAME
 ###     msc-prof-get - Get the profile of current system
 ###
@@ -22,17 +22,22 @@ MSC_LOG_PREFIX="[msc-prof-get] "
 ## Setup my-cfg-sys environment
 eval "$($(dirname $(realpath ${BASH_SOURCE[0]}))/msc-env-find -f)"
 ##== Function Start ==
-match_host(){
+match_host() {
     local pattern="$1"
-    if [[ $(hostname) != $pattern ]];then
+    if [[ $(hostname) != $pattern ]]; then
         return 1
     fi
     return 0
 }
 
-match_neigh_mac(){
+match_neigh_mac() {
     local pattern="$1"
-    for n in $(ip neigh show nud reachable|awk '{print $5}'); do
+    local neighbours=$(ip neigh show nud reachable)
+    neighbours+=$(ip neigh show nud stale)
+    if [ -z "${neighbours-}" ]; then
+        return 1
+    fi
+    for n in $(awk '{print $5}' <<<"$neighbours"); do
         if [[ $n == $pattern ]]; then
             return 0
         fi
@@ -40,15 +45,15 @@ match_neigh_mac(){
     return 1
 }
 
-match_usb(){
+match_usb() {
     local pattern="$1"
-    if lsusb -d $pattern > /dev/null; then
+    if lsusb -d $pattern >/dev/null; then
         return 0
     fi
     return 1
 }
 
-match_net_name(){
+match_net_name() {
     local pattern="$1"
     while read -r line; do
         if [[ $line == $pattern ]]; then
@@ -58,24 +63,24 @@ match_net_name(){
     return 1
 }
 
-match_file_contain(){
+match_file_contain() {
     local pattern="$1"
     local option="$2"
-    if [[ ! -e $pattern ]];then
+    if [[ ! -e $pattern ]]; then
         return 1
     fi
-    if [[ ! $(cat "$pattern") = $option ]];then
+    if [[ ! $(cat "$pattern") = $option ]]; then
         return 1
     fi
     return 0
 }
 
-match(){
+match() {
     local tag="$1"
     local category="$2"
     local pattern="$3"
     local option="${4:-}"
-    if eval "match_$(tr '[:upper:]' '[:lower:]'<<<$category) \"$pattern\" \"$option\"" ;then
+    if eval "match_$(tr '[:upper:]' '[:lower:]' <<<$category) \"$pattern\" \"$option\""; then
         msc_log "tag $tag matched category $category pattern $pattern"
         Result+="$tag+"
     fi
@@ -85,10 +90,9 @@ match(){
 Result='+'
 
 for feature_file in $MSC_ETC_MSC_DIR/features.d/*; do
-    while read -r line ; do
+    while read -r line; do
         IFS=$'\t' read -r -a tokens <<<"$line"
         match "${tokens[@]}"
     done < <(msc_file_list_effective "$feature_file")
 done
 echo $Result
-
